### ISSUE TITLE
Support response cache even when request uses authentication

### ISSUE THREAD

**Issue by joaoantunes** [yringler/distributed-middleware-cache#1]
All my requests on API need authentication because it uses Client Credentials Flow. 

I've tried using the distributed caching with Redis on anonymous requests and I see Redis being hit.
When I use all my other authenticated requests, it uses cache but I don't see Redis being hit.

I'm using Swagger for making the requests, and if I authenticate on Swagger and call an anonymous request the Redis is not being hit also. 

Any idea of how can I still use distributed cache on authorized requests?

**Comment by yringler** [comment]
As per [netcore docs](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-3.1#conditions-for-caching), response caching is disabled for authenticated requests (see there for details). This may explain the behavior you're seeing.

In terms of what to do - microsofts response cache middleware code takes care of that behaviour. In this project, a design decision I made is not to modify microsoft source.
This design means that the most streightforward solution, to fiddle with the middleware to also cache authenticated requests, isn't an option.
Possibly, we can fiddle with the request before passing it in to MS middleware code, perhaps [here](https://github.com/yringler/distributed-middleware-cache/blob/e4c972c3aa762b56f35cce241aea7ce96e9a801c/DistributedResponseCachingMiddleware/Distributed/DistributedResponseCachingMiddleware.cs#L36).
I don't know that I'll get around to adding such a feature myself, but you're welcome to open a PR, and I'll do my best to review/merge/release a new Nuget version in a timely fashion.

**Comment by yringler** [comment]
You are also welcome to fork this project, and include in it a copy of MS source which you can than modify according to your needs instead of using git submodules. If you're on a tight schedule etc, that would be the easiest option, althoughI find using git submodules more aesthetically pleasing, as well as making updates much more minimally invasive and flexible (changing to a different net core version just means changing the submodule commit).

**Comment by joaoantunes** [comment]
I've made some tests and I can confirm that if an Authorization Header is present it won't use caching.

A think a possible solution is to implement my own middleware (a simpler one) that allows this feature.

I found out this: https://stackoverflow.com/questions/57491941/how-to-allow-caching-api-endpoint-that-requires-authorization-header

I could add a feature to ResponseCachingPolicyProvider to allow authorized requests, but I can't change the behavior since is internal. 
Since this project can access the internals, it would make sense/possible in this project to allow defining our own custom ResponseCachingPolicyProvider? For example an AuthorizedResponseCachingPolicyProvider, that will allow it?

**Comment by yringler** [comment]
That's a great find! Yes, this won't be a problem at all to implement. The only question is the precise way to add that functionality to this project.
One thing I have to look into - on [github](https://github.com/dotnet/aspnetcore/blob/3.0/src/Middleware/ResponseCaching/src/ResponseCachingPolicyProvider.cs) it's internal, but in my submodule it's public. I must be at the wrong aspnetcore version.
I might get to add it in the next few days, or you are welcome to open a PR

**Comment by yringler** [comment]
But yes - within this library, you can inherit from an internal class and override any method

**Comment by joaoantunes** [comment]
Cool.
I've made a fork to validate the concept and it works!
You can check it on this [commit](https://github.com/joaoantunes/distributed-middleware-cache/commit/2e460373c3bf7160fb72bf850851e80975357dbb)

In the future to add more features/options may be a solution using a builder pattern, would make more sense.

**Comment by yringler** [comment]
I also was poking around, and created #2
Feel free to test/fork/add the sample.
A sample is definitely a very good thing to have.
Note that #2 updates to aspnetcore 3, so things are internal.
